### ISSUE TITLE
Custom Leave and Join Messages

### ISSUE THREAD

**Issue by dpvb** [dpvb/survival#45]

**Comment by dpvb** [comment]
Is this something that should be in the plugin - or should this be done elsewhere. @ms5984

**Comment by ms5984** [comment]
Either way. But if we do it in the plugin we can enable+disable with the GameManager 😄

**Comment by dpvb** [comment]
But since the Leave and Join affect the server as a whole, and not just the game, would that not make sense?

**Comment by ms5984** [comment]
Fair.
I guess I figured the messages would be more game-related. Could you share examples for each?

**Comment by dpvb** [comment]
This would be when they join and leave the server - not specifically the arena.

Would just look like this:
[+] {username}
[-] {username}

With custom colors too.

**Comment by ms5984** [comment]
We'll do this elsewhere. See #55

**Comment by ms5984** [comment]
Still need to be done. Does not involve #55 after all. I'd like us to make this either in the plugin or in a small custom plugin because I'd prefer the [access to Components](https://jd.papermc.io/paper/1.19/org/bukkit/event/player/PlayerJoinEvent.html#joinMessage(net.kyori.adventure.text.Component)) provided by Paper--which common Spigot plugins lack.
